### ISSUE TITLE
Pangeae DarwinCore failure

### ISSUE THREAD

**Issue by andrejjh** [frictionlessdata/FrictionlessDarwinCore#11]
fdwca fails to convert this darwincore from Pangeae.
```sh
fdwca http://digir.pangaea.de/dwca/?id=96900 pangeaeDP.zip
downloading http://digir.pangaea.de/dwca/?id=96900 as /var/folders/19/mrkkz1tx34l98n1rs3qr3xr00000gn/T/tmpglp_2ydl
(<class 'NameError'>, NameError("name 'eml' is not defined"), <traceback object at 0x10f193988>)
load zip failed
Traceback (most recent call last):
  File "/Users/ahe/test/bin/fdwca", line 10, in <module>
    sys.exit(cli())
  File "/Users/ahe/test/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ahe/test/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ahe/test/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ahe/test/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ahe/test/lib/python3.7/site-packages/FrictionlessDarwinCore/fdwca.py", line 13, in cli
    da.save(outpath)
  File "/Users/ahe/test/lib/python3.7/site-packages/FrictionlessDarwinCore/archive.py", line 74, in save
    zf.writestr('readme.md', self.metadata.as_markdown())
  File "/Users/ahe/test/lib/python3.7/site-packages/FrictionlessDarwinCore/metadata.py", line 48, in as_markdown
    return s.join(self.allLines)
TypeError: sequence item 11: expected str instance, NoneType found
```

**Comment by andrejjh** [comment]
Pangeae DwC had a  <geographicCoverage> element but no <geographicDescription>.
added 'if gd is not None:'
